import { useEffect, useState } from 'react'
import { setAuthToken, validateToken } from '@/lib/api'
import { setAuthStatus } from '@/lib/auth'
import { Button } from '@/components/common/Button'
import { ThemeToggle } from '@/components/layout/ThemeToggle'

// Centred, no-chrome login card. The dashboard token is generated by the
// backend at startup (search for "Dashboard access URL" in the server
// log). Pasting it once here persists to localStorage so the user does
// not have to repeat the URL trick.
interface LoginScreenProps {
  onSuccess?: () => void
}

export function LoginScreen({ onSuccess }: LoginScreenProps = {}) {
  const [token, setToken] = useState('')
  const [pending, setPending] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Drop the URL ?token= bootstrap leftover so the address bar is clean
  // when the LoginScreen rendered because of a 401 (rather than a fresh
  // visit). bootstrapAuth() in main.tsx already does this on first run;
  // running it again is a no-op when there is nothing to capture.
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    if (params.has('token')) {
      params.delete('token')
      const clean =
        window.location.pathname +
        (params.toString() ? '?' + params : '') +
        window.location.hash
      window.history.replaceState({}, '', clean)
    }
  }, [])

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    const t = token.trim()
    if (!t) {
      setError('Add meg a token-t.')
      return
    }
    setPending(true)
    setError(null)
    try {
      // Try the candidate token directly; only persist + flip if backend
      // accepts it. Avoids leaving a bad token in localStorage on paste
      // typos.
      const ok = await validateToken(t)
      if (!ok) {
        setError('A token érvénytelen vagy nincs jogosultsága.')
        setPending(false)
        return
      }
      setAuthToken(t)
      setAuthStatus('authenticated')
      onSuccess?.()
    } catch {
      setError('Nem sikerült kapcsolódni a backendhez.')
      setPending(false)
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-[var(--color-bg)] px-4 py-10">
      <div className="absolute right-4 top-4">
        <ThemeToggle />
      </div>
      <form
        onSubmit={submit}
        className="flex w-full max-w-md flex-col gap-4 rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-[var(--shadow-lg)]"
      >
        <header className="text-center">
          <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-[var(--color-accent)] text-xl font-bold text-white">
            M
          </div>
          <h1 className="text-xl font-semibold tracking-tight">
            Marveen Dashboard
          </h1>
          <p className="mt-1 text-sm text-[var(--color-text-muted)]">
            Jelentkezz be a dashboard tokennel.
          </p>
        </header>

        <label className="flex flex-col gap-1.5">
          <span className="text-[11px] font-medium uppercase tracking-wider text-[var(--color-text-muted)]">
            Token
          </span>
          <input
            type="password"
            autoFocus
            autoComplete="current-password"
            value={token}
            onChange={(e) => setToken(e.target.value)}
            placeholder="Illeszd be a backend access tokent"
            className="w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-[var(--color-input)] px-3 py-2 font-mono text-sm focus:border-[var(--color-accent)] focus:outline-none"
          />
        </label>

        {error ? (
          <div
            role="alert"
            className="rounded-[var(--radius-sm)] border border-[var(--color-danger)] bg-[var(--color-danger-soft)] px-3 py-2 text-sm text-[var(--color-danger)]"
          >
            {error}
          </div>
        ) : null}

        <Button
          type="submit"
          variant="primary"
          disabled={pending || !token.trim()}
          className="w-full justify-center"
        >
          {pending ? 'Ellenôrzés…' : 'Belépés'}
        </Button>

        <p className="text-[11px] leading-snug text-[var(--color-text-muted)]">
          A token a backend logban található:{' '}
          <code className="font-mono">Dashboard access URL</code> sor.
          Alternatívaként megnyithatod a teljes <code className="font-mono">?token=…</code> URL-t,
          a frontend automatikusan átveszi.
        </p>
      </form>
    </div>
  )
}
